### 登录
POST {{baseUrl}}/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "4297f44b13955235245b2497399d7a93"
}

### admin测试接口
GET {{baseUrl}}/admin/hello
Accept: application/json
Authorization: {{auth_token}}

### test测试接口
GET {{baseUrl}}/test/hello
Accept: application/json
Authorization: {{auth_token}}

### order测试接口
GET {{baseUrl}}/order/hello
Accept: application/json
Authorization: {{auth_token}}

### hi测试接口
GET {{baseUrl}}/hi/hello
Accept: application/json
Authorization: {{auth_token}}