### 登录
POST {{baseUrl}}/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "4297f44b13955235245b2497399d7a93"
}

### 测试接口
GET {{baseUrl}}/admin/hello
Accept: application/json
Authorization: {{auth_token}}

### 测试接口
GET {{baseUrl}}/test/hello
Accept: application/json
Authorization: {{auth_token}}