### 登录
POST {{baseUrl}}/admin/login
Content-Type: application/json

{
  "username": "JTADMIN",
  "password": "123123"
}

### 测试接口
GET {{baseUrl}}/admin/hello
Accept: application/json
Authorization: {{auth_token}}