### 测试接口
GET http://localhost:8888/admin/hello
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJKVEFETUlOIiwiY3JlYXRlZCI6MTcxMTY3NTcwMDg1OSwiZXhwIjoxNzEyMjgwNTAwfQ.L_EstOEfsgD4F9PGZ9qrGl6i5ePjF3umHLGnedTjJA4elJU49KAS1MSSJCvSV2MpiLERdT_6lPDfVdh4PbJFUQ
