### 测试接口
GET http://localhost:8888/admin/hello
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJKVEFETUlOIiwiY3JlYXRlZCI6MTcxMTYxOTkzNTk5MCwiZXhwIjoxNzEyMjI0NzM1fQ._E7S0Dob506UflouEtcIFkM-0pDrVcRh6d2Z8fS_PE4abMTpzIFx_8YIPejbrDZVrXYXW5AezQEcK4xoZWseRw
