server:
  port: 8888

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: aed3fb28b921a579172c
            client-secret: 8a1dfd12e7ef4e696bdfc571cd43093282bca422
